#!/bin/bash
echo "=== Signature Fix Verification ==="
echo ""
echo "1. Gamma signature:"
grep "pub fn gamma" crates/mathhook-core/src/core/functions/gamma/mod.rs | head -1
echo ""
echo "2. Beta signature:"
grep "pub fn beta" crates/mathhook-core/src/core/functions/beta/mod.rs | head -1
echo ""
echo "3. Digamma signature:"
grep "pub fn digamma" crates/mathhook-core/src/core/functions/digamma/mod.rs | head -1
echo ""
echo "4. Error handling counts:"
echo "  Gamma MathError::Pole: $(grep -c 'MathError::Pole' crates/mathhook-core/src/core/functions/gamma/mod.rs)"
echo "  Beta MathError::DomainError: $(grep -c 'MathError::DomainError' crates/mathhook-core/src/core/functions/beta/mod.rs)"
echo "  Digamma MathError::Pole: $(grep -c 'MathError::Pole' crates/mathhook-core/src/core/functions/digamma/mod.rs)"
echo ""
echo "5. Test counts:"
echo "  Gamma tests: $(grep -c '^fn test_' crates/mathhook-core/src/core/functions/gamma/tests.rs)"
echo "  Beta tests: $(grep -c '^fn test_' crates/mathhook-core/src/core/functions/beta/tests.rs)"
echo "  Digamma tests: $(grep -c '^fn test_' crates/mathhook-core/src/core/functions/digamma/tests.rs)"
echo ""
echo "6. Error test assertions:"
echo "  Gamma .is_err(): $(grep -c 'is_err()' crates/mathhook-core/src/core/functions/gamma/tests.rs)"
echo "  Beta .is_err(): $(grep -c 'is_err()' crates/mathhook-core/src/core/functions/beta/tests.rs)"
echo "  Digamma .is_err(): $(grep -c 'is_err()' crates/mathhook-core/src/core/functions/digamma/tests.rs)"
