#!/bin/bash
echo "=== Detailed Verification ==="
echo ""
echo "1. Checking Result<Expression, MathError> return types:"
echo ""
echo "Gamma returns:"
grep -A 2 "pub fn gamma" crates/mathhook-core/src/core/functions/gamma/mod.rs | grep "Result<Expression, MathError>"
echo ""
echo "Beta returns:"
grep -A 2 "pub fn beta" crates/mathhook-core/src/core/functions/beta/mod.rs | grep "Result<Expression, MathError>"
echo ""
echo "Digamma returns:"
grep -A 2 "pub fn digamma" crates/mathhook-core/src/core/functions/digamma/mod.rs | grep "Result<Expression, MathError>"
echo ""
echo "2. Checking Ok() wrapping in return statements:"
echo "  Gamma Ok() count: $(grep -c 'return Ok(' crates/mathhook-core/src/core/functions/gamma/mod.rs)"
echo "  Beta Ok() count: $(grep -c 'return Ok(' crates/mathhook-core/src/core/functions/beta/mod.rs)"
echo "  Digamma Ok() count: $(grep -c 'return Ok(' crates/mathhook-core/src/core/functions/digamma/mod.rs)"
echo ""
echo "3. Checking Err() returns for domain errors:"
echo "  Gamma Err() count: $(grep -c 'return Err(' crates/mathhook-core/src/core/functions/gamma/mod.rs)"
echo "  Beta Err() count: $(grep -c 'return Err(' crates/mathhook-core/src/core/functions/beta/mod.rs)"
echo "  Digamma Err() count: $(grep -c 'return Err(' crates/mathhook-core/src/core/functions/digamma/mod.rs)"
echo ""
echo "4. Verifying ? operator usage in beta (for gamma calls):"
grep -n "gamma(.*)?;" crates/mathhook-core/src/core/functions/beta/mod.rs || echo "  Found ? operator usage"
echo ""
echo "5. Checking test updates with .unwrap():"
echo "  Gamma .unwrap() in tests: $(grep -c '\.unwrap()' crates/mathhook-core/src/core/functions/gamma/tests.rs)"
echo "  Beta .unwrap() in tests: $(grep -c '\.unwrap()' crates/mathhook-core/src/core/functions/beta/tests.rs)"
echo "  Digamma .unwrap() in tests: $(grep -c '\.unwrap()' crates/mathhook-core/src/core/functions/digamma/tests.rs)"
echo ""
echo "6. Sample error messages:"
echo ""
echo "Gamma pole error:"
grep -A 2 "MathError::Pole" crates/mathhook-core/src/core/functions/gamma/mod.rs | head -4
echo ""
echo "Beta domain error:"
grep -A 3 "MathError::DomainError" crates/mathhook-core/src/core/functions/beta/mod.rs | head -5
