// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./mathhook-node.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('mathhook-node-android-arm64')
        const bindingPackageVersion = require('mathhook-node-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./mathhook-node.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('mathhook-node-android-arm-eabi')
        const bindingPackageVersion = require('mathhook-node-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (process.config?.variables?.shlib_suffix === 'dll.a' || process.config?.variables?.node_target_type === 'shared_library') {
        try {
        return require('./mathhook-node.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('mathhook-node-win32-x64-gnu')
        const bindingPackageVersion = require('mathhook-node-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./mathhook-node.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('mathhook-node-win32-x64-msvc')
        const bindingPackageVersion = require('mathhook-node-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./mathhook-node.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('mathhook-node-win32-ia32-msvc')
        const bindingPackageVersion = require('mathhook-node-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./mathhook-node.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('mathhook-node-win32-arm64-msvc')
        const bindingPackageVersion = require('mathhook-node-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./mathhook-node.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('mathhook-node-darwin-universal')
      const bindingPackageVersion = require('mathhook-node-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./mathhook-node.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('mathhook-node-darwin-x64')
        const bindingPackageVersion = require('mathhook-node-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./mathhook-node.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('mathhook-node-darwin-arm64')
        const bindingPackageVersion = require('mathhook-node-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./mathhook-node.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('mathhook-node-freebsd-x64')
        const bindingPackageVersion = require('mathhook-node-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./mathhook-node.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('mathhook-node-freebsd-arm64')
        const bindingPackageVersion = require('mathhook-node-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./mathhook-node.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('mathhook-node-linux-x64-musl')
          const bindingPackageVersion = require('mathhook-node-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./mathhook-node.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('mathhook-node-linux-x64-gnu')
          const bindingPackageVersion = require('mathhook-node-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./mathhook-node.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('mathhook-node-linux-arm64-musl')
          const bindingPackageVersion = require('mathhook-node-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./mathhook-node.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('mathhook-node-linux-arm64-gnu')
          const bindingPackageVersion = require('mathhook-node-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./mathhook-node.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('mathhook-node-linux-arm-musleabihf')
          const bindingPackageVersion = require('mathhook-node-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./mathhook-node.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('mathhook-node-linux-arm-gnueabihf')
          const bindingPackageVersion = require('mathhook-node-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./mathhook-node.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('mathhook-node-linux-loong64-musl')
          const bindingPackageVersion = require('mathhook-node-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./mathhook-node.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('mathhook-node-linux-loong64-gnu')
          const bindingPackageVersion = require('mathhook-node-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./mathhook-node.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('mathhook-node-linux-riscv64-musl')
          const bindingPackageVersion = require('mathhook-node-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./mathhook-node.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('mathhook-node-linux-riscv64-gnu')
          const bindingPackageVersion = require('mathhook-node-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./mathhook-node.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('mathhook-node-linux-ppc64-gnu')
        const bindingPackageVersion = require('mathhook-node-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./mathhook-node.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('mathhook-node-linux-s390x-gnu')
        const bindingPackageVersion = require('mathhook-node-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./mathhook-node.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('mathhook-node-openharmony-arm64')
        const bindingPackageVersion = require('mathhook-node-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./mathhook-node.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('mathhook-node-openharmony-x64')
        const bindingPackageVersion = require('mathhook-node-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./mathhook-node.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('mathhook-node-openharmony-arm')
        const bindingPackageVersion = require('mathhook-node-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.1.2' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.2 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./mathhook-node.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding) {
    try {
      wasiBinding = require('mathhook-node-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        wasiBindingError.cause = err
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.AbsoluteValueIntelligence = nativeBinding.AbsoluteValueIntelligence
module.exports.JsAbsoluteValueIntelligence = nativeBinding.JsAbsoluteValueIntelligence
module.exports.AbsSimplificationStrategy = nativeBinding.AbsSimplificationStrategy
module.exports.JsAbsSimplificationStrategy = nativeBinding.JsAbsSimplificationStrategy
module.exports.AccuracyVerifier = nativeBinding.AccuracyVerifier
module.exports.JsAccuracyVerifier = nativeBinding.JsAccuracyVerifier
module.exports.AdaptiveConfig = nativeBinding.AdaptiveConfig
module.exports.JsAdaptiveConfig = nativeBinding.JsAdaptiveConfig
module.exports.AdaptiveSimpson = nativeBinding.AdaptiveSimpson
module.exports.JsAdaptiveSimpson = nativeBinding.JsAdaptiveSimpson
module.exports.AdaptiveThresholds = nativeBinding.AdaptiveThresholds
module.exports.JsAdaptiveThresholds = nativeBinding.JsAdaptiveThresholds
module.exports.AntiderivativeRule = nativeBinding.AntiderivativeRule
module.exports.JsAntiderivativeRule = nativeBinding.JsAntiderivativeRule
module.exports.AntiderivativeRuleType = nativeBinding.AntiderivativeRuleType
module.exports.JsAntiderivativeRuleType = nativeBinding.JsAntiderivativeRuleType
module.exports.BackgroundCompute = nativeBinding.BackgroundCompute
module.exports.JsBackgroundCompute = nativeBinding.JsBackgroundCompute
module.exports.BackgroundComputeStatistics = nativeBinding.BackgroundComputeStatistics
module.exports.JsBackgroundComputeStatistics = nativeBinding.JsBackgroundComputeStatistics
module.exports.BernoulliODESolver = nativeBinding.BernoulliODESolver
module.exports.JsBernoulliODESolver = nativeBinding.JsBernoulliODESolver
module.exports.BindingContext = nativeBinding.BindingContext
module.exports.JsBindingContext = nativeBinding.JsBindingContext
module.exports.BisectionMethod = nativeBinding.BisectionMethod
module.exports.JsBisectionMethod = nativeBinding.JsBisectionMethod
module.exports.BoundaryCondition = nativeBinding.BoundaryCondition
module.exports.JsBoundaryCondition = nativeBinding.JsBoundaryCondition
module.exports.BoundaryLocation = nativeBinding.BoundaryLocation
module.exports.JsBoundaryLocation = nativeBinding.JsBoundaryLocation
module.exports.CacheStatistics = nativeBinding.CacheStatistics
module.exports.JsCacheStatistics = nativeBinding.JsCacheStatistics
module.exports.CacheStats = nativeBinding.CacheStats
module.exports.JsCacheStats = nativeBinding.JsCacheStats
module.exports.CharacteristicPolynomial = nativeBinding.CharacteristicPolynomial
module.exports.JsCharacteristicPolynomial = nativeBinding.JsCharacteristicPolynomial
module.exports.CharacteristicsError = nativeBinding.CharacteristicsError
module.exports.JsCharacteristicsError = nativeBinding.JsCharacteristicsError
module.exports.CharacteristicSolution = nativeBinding.CharacteristicSolution
module.exports.JsCharacteristicSolution = nativeBinding.JsCharacteristicSolution
module.exports.ChebyshevIntelligence = nativeBinding.ChebyshevIntelligence
module.exports.JsChebyshevIntelligence = nativeBinding.JsChebyshevIntelligence
module.exports.ChebyshevT = nativeBinding.ChebyshevT
module.exports.JsChebyshevT = nativeBinding.JsChebyshevT
module.exports.ChebyshevU = nativeBinding.ChebyshevU
module.exports.JsChebyshevU = nativeBinding.JsChebyshevU
module.exports.CholeskyDecomposition = nativeBinding.CholeskyDecomposition
module.exports.JsCholeskyDecomposition = nativeBinding.JsCholeskyDecomposition
module.exports.Commutativity = nativeBinding.Commutativity
module.exports.JsCommutativity = nativeBinding.JsCommutativity
module.exports.CompatibilityInfo = nativeBinding.CompatibilityInfo
module.exports.JsCompatibilityInfo = nativeBinding.JsCompatibilityInfo
module.exports.ComplexEigenDecomposition = nativeBinding.ComplexEigenDecomposition
module.exports.JsComplexEigenDecomposition = nativeBinding.JsComplexEigenDecomposition
module.exports.ComplexEigenvalue = nativeBinding.ComplexEigenvalue
module.exports.JsComplexEigenvalue = nativeBinding.JsComplexEigenvalue
module.exports.ComplexityEstimate = nativeBinding.ComplexityEstimate
module.exports.JsComplexityEstimate = nativeBinding.JsComplexityEstimate
module.exports.ComputePriority = nativeBinding.ComputePriority
module.exports.JsComputePriority = nativeBinding.JsComputePriority
module.exports.ComputeResult = nativeBinding.ComputeResult
module.exports.JsComputeResult = nativeBinding.JsComputeResult
module.exports.ComputeTask = nativeBinding.ComputeTask
module.exports.JsComputeTask = nativeBinding.JsComputeTask
module.exports.ConfigInfo = nativeBinding.ConfigInfo
module.exports.JsConfigInfo = nativeBinding.JsConfigInfo
module.exports.ConstantCoeffSecondOrderSolver = nativeBinding.ConstantCoeffSecondOrderSolver
module.exports.JsConstantCoeffSecondOrderSolver = nativeBinding.JsConstantCoeffSecondOrderSolver
module.exports.ConstantOfIntegration = nativeBinding.ConstantOfIntegration
module.exports.JsConstantOfIntegration = nativeBinding.JsConstantOfIntegration
module.exports.ConvergenceResult = nativeBinding.ConvergenceResult
module.exports.JsConvergenceResult = nativeBinding.JsConvergenceResult
module.exports.CosSimplificationStrategy = nativeBinding.CosSimplificationStrategy
module.exports.JsCosSimplificationStrategy = nativeBinding.JsCosSimplificationStrategy
module.exports.DefaultValidator = nativeBinding.DefaultValidator
module.exports.JsDefaultValidator = nativeBinding.JsDefaultValidator
module.exports.DerivativeRule = nativeBinding.DerivativeRule
module.exports.JsDerivativeRule = nativeBinding.JsDerivativeRule
module.exports.DerivativeRuleType = nativeBinding.DerivativeRuleType
module.exports.JsDerivativeRuleType = nativeBinding.JsDerivativeRuleType
module.exports.DifferentialEquation = nativeBinding.DifferentialEquation
module.exports.JsDifferentialEquation = nativeBinding.JsDifferentialEquation
module.exports.DifferentialExtension = nativeBinding.DifferentialExtension
module.exports.JsDifferentialExtension = nativeBinding.JsDifferentialExtension
module.exports.Domain = nativeBinding.Domain
module.exports.JsDomain = nativeBinding.JsDomain
module.exports.EducationalMessageGenerator = nativeBinding.EducationalMessageGenerator
module.exports.JsEducationalMessageGenerator = nativeBinding.JsEducationalMessageGenerator
module.exports.EducationalODESolver = nativeBinding.EducationalODESolver
module.exports.JsEducationalODESolver = nativeBinding.JsEducationalODESolver
module.exports.EducationalPDESolver = nativeBinding.EducationalPDESolver
module.exports.JsEducationalPDESolver = nativeBinding.JsEducationalPDESolver
module.exports.EigenDecomposition = nativeBinding.EigenDecomposition
module.exports.JsEigenDecomposition = nativeBinding.JsEigenDecomposition
module.exports.EigenvalueSolution = nativeBinding.EigenvalueSolution
module.exports.JsEigenvalueSolution = nativeBinding.JsEigenvalueSolution
module.exports.ElementaryIntelligence = nativeBinding.ElementaryIntelligence
module.exports.JsElementaryIntelligence = nativeBinding.JsElementaryIntelligence
module.exports.ElementaryProperties = nativeBinding.ElementaryProperties
module.exports.JsElementaryProperties = nativeBinding.JsElementaryProperties
module.exports.EquationAnalyzer = nativeBinding.EquationAnalyzer
module.exports.JsEquationAnalyzer = nativeBinding.JsEquationAnalyzer
module.exports.EquationType = nativeBinding.EquationType
module.exports.JsEquationType = nativeBinding.JsEquationType
module.exports.EvalContext = nativeBinding.EvalContext
module.exports.JsEvalContext = nativeBinding.JsEvalContext
module.exports.EvaluationMethod = nativeBinding.EvaluationMethod
module.exports.JsEvaluationMethod = nativeBinding.JsEvaluationMethod
module.exports.EvaluationResult = nativeBinding.EvaluationResult
module.exports.JsEvaluationResult = nativeBinding.JsEvaluationResult
module.exports.EvaluationStrategy = nativeBinding.EvaluationStrategy
module.exports.JsEvaluationStrategy = nativeBinding.JsEvaluationStrategy
module.exports.ExactODESolver = nativeBinding.ExactODESolver
module.exports.JsExactODESolver = nativeBinding.JsExactODESolver
module.exports.ExponentialIntelligence = nativeBinding.ExponentialIntelligence
module.exports.JsExponentialIntelligence = nativeBinding.JsExponentialIntelligence
module.exports.Expression = nativeBinding.Expression
module.exports.JsExpression = nativeBinding.JsExpression
module.exports.ExpressionClass = nativeBinding.ExpressionClass
module.exports.JsExpressionClass = nativeBinding.JsExpressionClass
module.exports.ExpSimplificationStrategy = nativeBinding.ExpSimplificationStrategy
module.exports.JsExpSimplificationStrategy = nativeBinding.JsExpSimplificationStrategy
module.exports.ExtensionError = nativeBinding.ExtensionError
module.exports.JsExtensionError = nativeBinding.JsExtensionError
module.exports.ExtensionRegistry = nativeBinding.ExtensionRegistry
module.exports.JsExtensionRegistry = nativeBinding.JsExtensionRegistry
module.exports.FactorialSimplificationStrategy = nativeBinding.FactorialSimplificationStrategy
module.exports.JsFactorialSimplificationStrategy = nativeBinding.JsFactorialSimplificationStrategy
module.exports.FiniteFieldError = nativeBinding.FiniteFieldError
module.exports.JsFiniteFieldError = nativeBinding.JsFiniteFieldError
module.exports.FormattingError = nativeBinding.FormattingError
module.exports.JsFormattingError = nativeBinding.JsFormattingError
module.exports.FunctionEducator = nativeBinding.FunctionEducator
module.exports.JsFunctionEducator = nativeBinding.JsFunctionEducator
module.exports.FunctionFamily = nativeBinding.FunctionFamily
module.exports.JsFunctionFamily = nativeBinding.JsFunctionFamily
module.exports.FunctionProperties = nativeBinding.FunctionProperties
module.exports.JsFunctionProperties = nativeBinding.JsFunctionProperties
module.exports.GammaSimplificationStrategy = nativeBinding.GammaSimplificationStrategy
module.exports.JsGammaSimplificationStrategy = nativeBinding.JsGammaSimplificationStrategy
module.exports.GaussianQuadrature = nativeBinding.GaussianQuadrature
module.exports.JsGaussianQuadrature = nativeBinding.JsGaussianQuadrature
module.exports.GeneratingFunction = nativeBinding.GeneratingFunction
module.exports.JsGeneratingFunction = nativeBinding.JsGeneratingFunction
module.exports.GeneratingFunctionType = nativeBinding.GeneratingFunctionType
module.exports.JsGeneratingFunctionType = nativeBinding.JsGeneratingFunctionType
module.exports.GenericTrigSimplificationStrategy = nativeBinding.GenericTrigSimplificationStrategy
module.exports.JsGenericTrigSimplificationStrategy = nativeBinding.JsGenericTrigSimplificationStrategy
module.exports.GpuAccelerator = nativeBinding.GpuAccelerator
module.exports.JsGpuAccelerator = nativeBinding.JsGpuAccelerator
module.exports.GpuBackend = nativeBinding.GpuBackend
module.exports.JsGpuBackend = nativeBinding.JsGpuBackend
module.exports.GpuCapabilities = nativeBinding.GpuCapabilities
module.exports.JsGpuCapabilities = nativeBinding.JsGpuCapabilities
module.exports.GpuOperation = nativeBinding.GpuOperation
module.exports.JsGpuOperation = nativeBinding.JsGpuOperation
module.exports.GpuStatistics = nativeBinding.GpuStatistics
module.exports.JsGpuStatistics = nativeBinding.JsGpuStatistics
module.exports.GpuThresholds = nativeBinding.GpuThresholds
module.exports.JsGpuThresholds = nativeBinding.JsGpuThresholds
module.exports.GroebnerBasis = nativeBinding.GroebnerBasis
module.exports.JsGroebnerBasis = nativeBinding.JsGroebnerBasis
module.exports.HeatEquationSolver = nativeBinding.HeatEquationSolver
module.exports.JsHeatEquationSolver = nativeBinding.JsHeatEquationSolver
module.exports.Hermite = nativeBinding.Hermite
module.exports.JsHermite = nativeBinding.JsHermite
module.exports.HermiteIntelligence = nativeBinding.HermiteIntelligence
module.exports.JsHermiteIntelligence = nativeBinding.JsHermiteIntelligence
module.exports.HeuristicGCDFailed = nativeBinding.HeuristicGCDFailed
module.exports.JsHeuristicGCDFailed = nativeBinding.JsHeuristicGCDFailed
module.exports.HomogeneousODESolver = nativeBinding.HomogeneousODESolver
module.exports.JsHomogeneousODESolver = nativeBinding.JsHomogeneousODESolver
module.exports.HyperbolicIntelligence = nativeBinding.HyperbolicIntelligence
module.exports.JsHyperbolicIntelligence = nativeBinding.JsHyperbolicIntelligence
module.exports.ImplicitMultiplicationProcessor = nativeBinding.ImplicitMultiplicationProcessor
module.exports.JsImplicitMultiplicationProcessor = nativeBinding.JsImplicitMultiplicationProcessor
module.exports.InitialCondition = nativeBinding.InitialCondition
module.exports.JsInitialCondition = nativeBinding.JsInitialCondition
module.exports.IntegrationByParts = nativeBinding.IntegrationByParts
module.exports.JsIntegrationByParts = nativeBinding.JsIntegrationByParts
module.exports.IntegrationConfig = nativeBinding.IntegrationConfig
module.exports.JsIntegrationConfig = nativeBinding.JsIntegrationConfig
module.exports.IntegrationExplanation = nativeBinding.IntegrationExplanation
module.exports.JsIntegrationExplanation = nativeBinding.JsIntegrationExplanation
module.exports.IntegrationMethods = nativeBinding.IntegrationMethods
module.exports.JsIntegrationMethods = nativeBinding.JsIntegrationMethods
module.exports.IntegrationResult = nativeBinding.IntegrationResult
module.exports.JsIntegrationResult = nativeBinding.JsIntegrationResult
module.exports.IntegrationStrategy = nativeBinding.IntegrationStrategy
module.exports.JsIntegrationStrategy = nativeBinding.JsIntegrationStrategy
module.exports.IntelligenceConfig = nativeBinding.IntelligenceConfig
module.exports.JsIntelligenceConfig = nativeBinding.JsIntelligenceConfig
module.exports.IntelligenceReport = nativeBinding.IntelligenceReport
module.exports.JsIntelligenceReport = nativeBinding.JsIntelligenceReport
module.exports.IssueSeverity = nativeBinding.IssueSeverity
module.exports.JsIssueSeverity = nativeBinding.JsIssueSeverity
module.exports.Laguerre = nativeBinding.Laguerre
module.exports.JsLaguerre = nativeBinding.JsLaguerre
module.exports.LaguerreIntelligence = nativeBinding.LaguerreIntelligence
module.exports.JsLaguerreIntelligence = nativeBinding.JsLaguerreIntelligence
module.exports.LaplaceEquationSolver = nativeBinding.LaplaceEquationSolver
module.exports.JsLaplaceEquationSolver = nativeBinding.JsLaplaceEquationSolver
module.exports.LaplaceSolution = nativeBinding.LaplaceSolution
module.exports.JsLaplaceSolution = nativeBinding.JsLaplaceSolution
module.exports.LaTeXContext = nativeBinding.LaTeXContext
module.exports.JsLaTeXContext = nativeBinding.JsLaTeXContext
module.exports.Legendre = nativeBinding.Legendre
module.exports.JsLegendre = nativeBinding.JsLegendre
module.exports.LegendreIntelligence = nativeBinding.LegendreIntelligence
module.exports.JsLegendreIntelligence = nativeBinding.JsLegendreIntelligence
module.exports.LimitDirection = nativeBinding.LimitDirection
module.exports.JsLimitDirection = nativeBinding.JsLimitDirection
module.exports.LimitEducation = nativeBinding.LimitEducation
module.exports.JsLimitEducation = nativeBinding.JsLimitEducation
module.exports.LimitMethods = nativeBinding.LimitMethods
module.exports.JsLimitMethods = nativeBinding.JsLimitMethods
module.exports.LinearFirstOrderSolver = nativeBinding.LinearFirstOrderSolver
module.exports.JsLinearFirstOrderSolver = nativeBinding.JsLinearFirstOrderSolver
module.exports.LinearSolver = nativeBinding.LinearSolver
module.exports.JsLinearSolver = nativeBinding.JsLinearSolver
module.exports.LinearSystemSolver = nativeBinding.LinearSystemSolver
module.exports.JsLinearSystemSolver = nativeBinding.JsLinearSystemSolver
module.exports.LinearTerm = nativeBinding.LinearTerm
module.exports.JsLinearTerm = nativeBinding.JsLinearTerm
module.exports.LogarithmicIntelligence = nativeBinding.LogarithmicIntelligence
module.exports.JsLogarithmicIntelligence = nativeBinding.JsLogarithmicIntelligence
module.exports.LogarithmSimplificationStrategy = nativeBinding.LogarithmSimplificationStrategy
module.exports.JsLogarithmSimplificationStrategy = nativeBinding.JsLogarithmSimplificationStrategy
module.exports.LUDecomposition = nativeBinding.LUDecomposition
module.exports.JsLUDecomposition = nativeBinding.JsLUDecomposition
module.exports.MathConstant = nativeBinding.MathConstant
module.exports.JsMathConstant = nativeBinding.JsMathConstant
module.exports.MathIdentity = nativeBinding.MathIdentity
module.exports.JsMathIdentity = nativeBinding.JsMathIdentity
module.exports.MathLanguage = nativeBinding.MathLanguage
module.exports.JsMathLanguage = nativeBinding.JsMathLanguage
module.exports.MathSerializer = nativeBinding.MathSerializer
module.exports.JsMathSerializer = nativeBinding.JsMathSerializer
module.exports.Matrix = nativeBinding.Matrix
module.exports.JsMatrix = nativeBinding.JsMatrix
module.exports.MatrixEquationSolver = nativeBinding.MatrixEquationSolver
module.exports.JsMatrixEquationSolver = nativeBinding.JsMatrixEquationSolver
module.exports.MessageCategory = nativeBinding.MessageCategory
module.exports.JsMessageCategory = nativeBinding.JsMessageCategory
module.exports.MessageHashSystem = nativeBinding.MessageHashSystem
module.exports.JsMessageHashSystem = nativeBinding.JsMessageHashSystem
module.exports.MessageOptimizer = nativeBinding.MessageOptimizer
module.exports.JsMessageOptimizer = nativeBinding.JsMessageOptimizer
module.exports.MessageTemplate = nativeBinding.MessageTemplate
module.exports.JsMessageTemplate = nativeBinding.JsMessageTemplate
module.exports.MessageType = nativeBinding.MessageType
module.exports.JsMessageType = nativeBinding.JsMessageType
module.exports.NaturalLogSimplificationStrategy = nativeBinding.NaturalLogSimplificationStrategy
module.exports.JsNaturalLogSimplificationStrategy = nativeBinding.JsNaturalLogSimplificationStrategy
module.exports.NewtonRaphson = nativeBinding.NewtonRaphson
module.exports.JsNewtonRaphson = nativeBinding.JsNewtonRaphson
module.exports.NumberTheoryIntelligence = nativeBinding.NumberTheoryIntelligence
module.exports.JsNumberTheoryIntelligence = nativeBinding.JsNumberTheoryIntelligence
module.exports.NumericMatrix = nativeBinding.NumericMatrix
module.exports.JsNumericMatrix = nativeBinding.JsNumericMatrix
module.exports.ODEClassifier = nativeBinding.ODEClassifier
module.exports.JsODEClassifier = nativeBinding.JsODEClassifier
module.exports.ODEExamples = nativeBinding.ODEExamples
module.exports.JsODEExamples = nativeBinding.JsODEExamples
module.exports.ODEExplanation = nativeBinding.ODEExplanation
module.exports.JsODEExplanation = nativeBinding.JsODEExplanation
module.exports.ODEPhase = nativeBinding.ODEPhase
module.exports.JsODEPhase = nativeBinding.JsODEPhase
module.exports.ODESolution = nativeBinding.ODESolution
module.exports.JsODESolution = nativeBinding.JsODESolution
module.exports.ODESolutionStep = nativeBinding.ODESolutionStep
module.exports.JsODESolutionStep = nativeBinding.JsODESolutionStep
module.exports.ODESolver = nativeBinding.ODESolver
module.exports.JsODESolver = nativeBinding.JsODESolver
module.exports.ODESolverRegistry = nativeBinding.ODESolverRegistry
module.exports.JsODESolverRegistry = nativeBinding.JsODESolverRegistry
module.exports.ODEStepFactory = nativeBinding.ODEStepFactory
module.exports.JsODEStepFactory = nativeBinding.JsODEStepFactory
module.exports.ODEType = nativeBinding.ODEType
module.exports.JsODEType = nativeBinding.JsODEType
module.exports.OperationContext = nativeBinding.OperationContext
module.exports.JsOperationContext = nativeBinding.JsOperationContext
module.exports.ParallelStatistics = nativeBinding.ParallelStatistics
module.exports.JsParallelStatistics = nativeBinding.JsParallelStatistics
module.exports.ParseError = nativeBinding.ParseError
module.exports.JsParseError = nativeBinding.JsParseError
module.exports.Parser = nativeBinding.Parser
module.exports.JsParser = nativeBinding.JsParser
module.exports.ParserConfig = nativeBinding.ParserConfig
module.exports.JsParserConfig = nativeBinding.JsParserConfig
module.exports.PartialFractionDecomposition = nativeBinding.PartialFractionDecomposition
module.exports.JsPartialFractionDecomposition = nativeBinding.JsPartialFractionDecomposition
module.exports.PatternKey = nativeBinding.PatternKey
module.exports.JsPatternKey = nativeBinding.JsPatternKey
module.exports.Pde = nativeBinding.Pde
module.exports.JsPde = nativeBinding.JsPde
module.exports.PdeCoefficients = nativeBinding.PdeCoefficients
module.exports.JsPdeCoefficients = nativeBinding.JsPdeCoefficients
module.exports.PdeLinearity = nativeBinding.PdeLinearity
module.exports.JsPdeLinearity = nativeBinding.JsPdeLinearity
module.exports.PdeMessageKey = nativeBinding.PdeMessageKey
module.exports.JsPdeMessageKey = nativeBinding.JsPdeMessageKey
module.exports.PdeMessageVariant = nativeBinding.PdeMessageVariant
module.exports.JsPdeMessageVariant = nativeBinding.JsPdeMessageVariant
module.exports.PdeOrder = nativeBinding.PdeOrder
module.exports.JsPdeOrder = nativeBinding.JsPdeOrder
module.exports.PDESolution = nativeBinding.PDESolution
module.exports.JsPDESolution = nativeBinding.JsPDESolution
module.exports.PDESolverRegistry = nativeBinding.PDESolverRegistry
module.exports.JsPDESolverRegistry = nativeBinding.JsPDESolverRegistry
module.exports.PdeType = nativeBinding.PdeType
module.exports.JsPdeType = nativeBinding.JsPdeType
module.exports.PerformanceConfig = nativeBinding.PerformanceConfig
module.exports.JsPerformanceConfig = nativeBinding.JsPerformanceConfig
module.exports.PerformanceMeasurement = nativeBinding.PerformanceMeasurement
module.exports.JsPerformanceMeasurement = nativeBinding.JsPerformanceMeasurement
module.exports.PerformanceMetrics = nativeBinding.PerformanceMetrics
module.exports.JsPerformanceMetrics = nativeBinding.JsPerformanceMetrics
module.exports.PerformanceOptimizer = nativeBinding.PerformanceOptimizer
module.exports.JsPerformanceOptimizer = nativeBinding.JsPerformanceOptimizer
module.exports.PersistentCache = nativeBinding.PersistentCache
module.exports.JsPersistentCache = nativeBinding.JsPersistentCache
module.exports.PersistentCacheConfig = nativeBinding.PersistentCacheConfig
module.exports.JsPersistentCacheConfig = nativeBinding.JsPersistentCacheConfig
module.exports.PersistentCacheEntry = nativeBinding.PersistentCacheEntry
module.exports.JsPersistentCacheEntry = nativeBinding.JsPersistentCacheEntry
module.exports.PersistentCacheStatistics = nativeBinding.PersistentCacheStatistics
module.exports.JsPersistentCacheStatistics = nativeBinding.JsPersistentCacheStatistics
module.exports.PolynomialArithmetic = nativeBinding.PolynomialArithmetic
module.exports.JsPolynomialArithmetic = nativeBinding.JsPolynomialArithmetic
module.exports.PolynomialFamily = nativeBinding.PolynomialFamily
module.exports.JsPolynomialFamily = nativeBinding.JsPolynomialFamily
module.exports.PolynomialIntelligence = nativeBinding.PolynomialIntelligence
module.exports.JsPolynomialIntelligence = nativeBinding.JsPolynomialIntelligence
module.exports.PolynomialProperties = nativeBinding.PolynomialProperties
module.exports.JsPolynomialProperties = nativeBinding.JsPolynomialProperties
module.exports.ProfilerStatistics = nativeBinding.ProfilerStatistics
module.exports.JsProfilerStatistics = nativeBinding.JsProfilerStatistics
module.exports.QRDecomposition = nativeBinding.QRDecomposition
module.exports.JsQRDecomposition = nativeBinding.JsQRDecomposition
module.exports.QuadraticSolver = nativeBinding.QuadraticSolver
module.exports.JsQuadraticSolver = nativeBinding.JsQuadraticSolver
module.exports.QuadraticTerm = nativeBinding.QuadraticTerm
module.exports.JsQuadraticTerm = nativeBinding.JsQuadraticTerm
module.exports.Range = nativeBinding.Range
module.exports.JsRange = nativeBinding.JsRange
module.exports.RationalIntegral = nativeBinding.RationalIntegral
module.exports.JsRationalIntegral = nativeBinding.JsRationalIntegral
module.exports.RecurrenceRule = nativeBinding.RecurrenceRule
module.exports.JsRecurrenceRule = nativeBinding.JsRecurrenceRule
module.exports.Reference = nativeBinding.Reference
module.exports.JsReference = nativeBinding.JsReference
module.exports.RelationType = nativeBinding.RelationType
module.exports.JsRelationType = nativeBinding.JsRelationType
module.exports.ResidueMethods = nativeBinding.ResidueMethods
module.exports.JsResidueMethods = nativeBinding.JsResidueMethods
module.exports.RischResult = nativeBinding.RischResult
module.exports.JsRischResult = nativeBinding.JsRischResult
module.exports.RodriguesFormula = nativeBinding.RodriguesFormula
module.exports.JsRodriguesFormula = nativeBinding.JsRodriguesFormula
module.exports.RombergIntegration = nativeBinding.RombergIntegration
module.exports.JsRombergIntegration = nativeBinding.JsRombergIntegration
module.exports.RootFindingConfig = nativeBinding.RootFindingConfig
module.exports.JsRootFindingConfig = nativeBinding.JsRootFindingConfig
module.exports.RootType = nativeBinding.RootType
module.exports.JsRootType = nativeBinding.JsRootType
module.exports.RuntimeProfiler = nativeBinding.RuntimeProfiler
module.exports.JsRuntimeProfiler = nativeBinding.JsRuntimeProfiler
module.exports.SecantMethod = nativeBinding.SecantMethod
module.exports.JsSecantMethod = nativeBinding.JsSecantMethod
module.exports.SeparableODESolver = nativeBinding.SeparableODESolver
module.exports.JsSeparableODESolver = nativeBinding.JsSeparableODESolver
module.exports.SeparatedSolution = nativeBinding.SeparatedSolution
module.exports.JsSeparatedSolution = nativeBinding.JsSeparatedSolution
module.exports.SerializationError = nativeBinding.SerializationError
module.exports.JsSerializationError = nativeBinding.JsSerializationError
module.exports.SeriesMethods = nativeBinding.SeriesMethods
module.exports.JsSeriesMethods = nativeBinding.JsSeriesMethods
module.exports.SeriesType = nativeBinding.SeriesType
module.exports.JsSeriesType = nativeBinding.JsSeriesType
module.exports.SimdOptimized = nativeBinding.SimdOptimized
module.exports.JsSimdOptimized = nativeBinding.JsSimdOptimized
module.exports.SimdStatistics = nativeBinding.SimdStatistics
module.exports.JsSimdStatistics = nativeBinding.JsSimdStatistics
module.exports.SimpleContext = nativeBinding.SimpleContext
module.exports.JsSimpleContext = nativeBinding.JsSimpleContext
module.exports.SimplificationRegistry = nativeBinding.SimplificationRegistry
module.exports.JsSimplificationRegistry = nativeBinding.JsSimplificationRegistry
module.exports.SinSimplificationStrategy = nativeBinding.SinSimplificationStrategy
module.exports.JsSinSimplificationStrategy = nativeBinding.JsSinSimplificationStrategy
module.exports.SmartDisplayFormatter = nativeBinding.SmartDisplayFormatter
module.exports.JsSmartDisplayFormatter = nativeBinding.JsSmartDisplayFormatter
module.exports.SmartEquationSolver = nativeBinding.SmartEquationSolver
module.exports.JsSmartEquationSolver = nativeBinding.JsSmartEquationSolver
module.exports.SolutionMetadata = nativeBinding.SolutionMetadata
module.exports.JsSolutionMetadata = nativeBinding.JsSolutionMetadata
module.exports.SolverConfig = nativeBinding.SolverConfig
module.exports.JsSolverConfig = nativeBinding.JsSolverConfig
module.exports.SolverError = nativeBinding.SolverError
module.exports.JsSolverError = nativeBinding.JsSolverError
module.exports.SolverResult = nativeBinding.SolverResult
module.exports.JsSolverResult = nativeBinding.JsSolverResult
module.exports.SpecialIntelligence = nativeBinding.SpecialIntelligence
module.exports.JsSpecialIntelligence = nativeBinding.JsSpecialIntelligence
module.exports.SpecialProperties = nativeBinding.SpecialProperties
module.exports.JsSpecialProperties = nativeBinding.JsSpecialProperties
module.exports.SpecialStepGenerator = nativeBinding.SpecialStepGenerator
module.exports.JsSpecialStepGenerator = nativeBinding.JsSpecialStepGenerator
module.exports.SpecialValue = nativeBinding.SpecialValue
module.exports.JsSpecialValue = nativeBinding.JsSpecialValue
module.exports.SqrtIntelligence = nativeBinding.SqrtIntelligence
module.exports.JsSqrtIntelligence = nativeBinding.JsSqrtIntelligence
module.exports.SqrtSimplificationStrategy = nativeBinding.SqrtSimplificationStrategy
module.exports.JsSqrtSimplificationStrategy = nativeBinding.JsSqrtSimplificationStrategy
module.exports.StableCache = nativeBinding.StableCache
module.exports.JsStableCache = nativeBinding.JsStableCache
module.exports.StableMatrix = nativeBinding.StableMatrix
module.exports.JsStableMatrix = nativeBinding.JsStableMatrix
module.exports.StableSIMD = nativeBinding.StableSIMD
module.exports.JsStableSIMD = nativeBinding.JsStableSIMD
module.exports.Step = nativeBinding.Step
module.exports.JsStep = nativeBinding.JsStep
module.exports.StepByStepExplanation = nativeBinding.StepByStepExplanation
module.exports.JsStepByStepExplanation = nativeBinding.JsStepByStepExplanation
module.exports.StrategyContext = nativeBinding.StrategyContext
module.exports.JsStrategyContext = nativeBinding.JsStrategyContext
module.exports.SummationMethods = nativeBinding.SummationMethods
module.exports.JsSummationMethods = nativeBinding.JsSummationMethods
module.exports.SVDDecomposition = nativeBinding.SVDDecomposition
module.exports.JsSVDDecomposition = nativeBinding.JsSVDDecomposition
module.exports.Symbol = nativeBinding.Symbol
module.exports.JsSymbol = nativeBinding.JsSymbol
module.exports.SymbolicExpander = nativeBinding.SymbolicExpander
module.exports.JsSymbolicExpander = nativeBinding.JsSymbolicExpander
module.exports.SymbolType = nativeBinding.SymbolType
module.exports.JsSymbolType = nativeBinding.JsSymbolType
module.exports.SystemSolver = nativeBinding.SystemSolver
module.exports.JsSystemSolver = nativeBinding.JsSystemSolver
module.exports.TanSimplificationStrategy = nativeBinding.TanSimplificationStrategy
module.exports.JsTanSimplificationStrategy = nativeBinding.JsTanSimplificationStrategy
module.exports.ThreeTermRecurrence = nativeBinding.ThreeTermRecurrence
module.exports.JsThreeTermRecurrence = nativeBinding.JsThreeTermRecurrence
module.exports.TokenCategory = nativeBinding.TokenCategory
module.exports.JsTokenCategory = nativeBinding.JsTokenCategory
module.exports.TrigonometricIntelligence = nativeBinding.TrigonometricIntelligence
module.exports.JsTrigonometricIntelligence = nativeBinding.JsTrigonometricIntelligence
module.exports.UniversalFunctionRegistry = nativeBinding.UniversalFunctionRegistry
module.exports.JsUniversalFunctionRegistry = nativeBinding.JsUniversalFunctionRegistry
module.exports.UserProperties = nativeBinding.UserProperties
module.exports.JsUserProperties = nativeBinding.JsUserProperties
module.exports.UserProperty = nativeBinding.UserProperty
module.exports.JsUserProperty = nativeBinding.JsUserProperty
module.exports.ValidationIssue = nativeBinding.ValidationIssue
module.exports.JsValidationIssue = nativeBinding.JsValidationIssue
module.exports.ValidationLevel = nativeBinding.ValidationLevel
module.exports.JsValidationLevel = nativeBinding.JsValidationLevel
module.exports.ValidationMetrics = nativeBinding.ValidationMetrics
module.exports.JsValidationMetrics = nativeBinding.JsValidationMetrics
module.exports.ValidationResult = nativeBinding.ValidationResult
module.exports.JsValidationResult = nativeBinding.JsValidationResult
module.exports.VerifiedConstant = nativeBinding.VerifiedConstant
module.exports.JsVerifiedConstant = nativeBinding.JsVerifiedConstant
module.exports.VerifiedRelationship = nativeBinding.VerifiedRelationship
module.exports.JsVerifiedRelationship = nativeBinding.JsVerifiedRelationship
module.exports.Version = nativeBinding.Version
module.exports.JsVersion = nativeBinding.JsVersion
module.exports.WaveEquationSolver = nativeBinding.WaveEquationSolver
module.exports.JsWaveEquationSolver = nativeBinding.JsWaveEquationSolver
module.exports.WaveSolution = nativeBinding.WaveSolution
module.exports.JsWaveSolution = nativeBinding.JsWaveSolution
module.exports.WolframContext = nativeBinding.WolframContext
module.exports.JsWolframContext = nativeBinding.JsWolframContext
module.exports.abs = nativeBinding.abs
module.exports.acos = nativeBinding.acos
module.exports.algorithmOverview = nativeBinding.algorithmOverview
module.exports.asin = nativeBinding.asin
module.exports.assembleIntegral = nativeBinding.assembleIntegral
module.exports.atan = nativeBinding.atan
module.exports.besselJ = nativeBinding.besselJ
module.exports.besselY = nativeBinding.besselY
module.exports.beta = nativeBinding.beta
module.exports.betaNumerical = nativeBinding.betaNumerical
module.exports.buildCachedFunction = nativeBinding.buildCachedFunction
module.exports.buildExprList = nativeBinding.buildExprList
module.exports.buildExtensionTower = nativeBinding.buildExtensionTower
module.exports.cacheResult = nativeBinding.cacheResult
module.exports.cacheStats = nativeBinding.cacheStats
module.exports.ceil = nativeBinding.ceil
module.exports.classifyPde = nativeBinding.classifyPde
module.exports.clearBackgroundCompute = nativeBinding.clearBackgroundCompute
module.exports.clearCache = nativeBinding.clearCache
module.exports.clearCaches = nativeBinding.clearCaches
module.exports.clearPersistentCache = nativeBinding.clearPersistentCache
module.exports.computeExprHash = nativeBinding.computeExprHash
module.exports.computeHeavisideCoefficient = nativeBinding.computeHeavisideCoefficient
module.exports.cos = nativeBinding.cos
module.exports.cosh = nativeBinding.cosh
module.exports.degree = nativeBinding.degree
module.exports.degree = nativeBinding.degree
module.exports.digamma = nativeBinding.digamma
module.exports.digammaNumerical = nativeBinding.digammaNumerical
module.exports.erf = nativeBinding.erf
module.exports.erfc = nativeBinding.erfc
module.exports.evaluateRecurrence = nativeBinding.evaluateRecurrence
module.exports.exp = nativeBinding.exp
module.exports.expand = nativeBinding.expand
module.exports.expandChebyshevFirstSymbolic = nativeBinding.expandChebyshevFirstSymbolic
module.exports.expandChebyshevSecondSymbolic = nativeBinding.expandChebyshevSecondSymbolic
module.exports.expandHermiteSymbolic = nativeBinding.expandHermiteSymbolic
module.exports.expandLaguerreSymbolic = nativeBinding.expandLaguerreSymbolic
module.exports.expandLegendreSymbolic = nativeBinding.expandLegendreSymbolic
module.exports.explainAlgorithmSelection = nativeBinding.explainAlgorithmSelection
module.exports.explainConstantRule = nativeBinding.explainConstantRule
module.exports.explainContentExtraction = nativeBinding.explainContentExtraction
module.exports.explainCrtReconstruction = nativeBinding.explainCrtReconstruction
module.exports.explainDefiniteIntegral = nativeBinding.explainDefiniteIntegral
module.exports.explainIntegrationByParts = nativeBinding.explainIntegrationByParts
module.exports.explainIterationStep = nativeBinding.explainIterationStep
module.exports.explainMultivariateEvaluation = nativeBinding.explainMultivariateEvaluation
module.exports.explainPolyDivisionImpl = nativeBinding.explainPolyDivisionImpl
module.exports.explainPolyFactorizationImpl = nativeBinding.explainPolyFactorizationImpl
module.exports.explainPolyGcdImpl = nativeBinding.explainPolyGcdImpl
module.exports.explainPowerRule = nativeBinding.explainPowerRule
module.exports.explainSelectionRationale = nativeBinding.explainSelectionRationale
module.exports.explainSparseOptimization = nativeBinding.explainSparseOptimization
module.exports.explainTrialDivision = nativeBinding.explainTrialDivision
module.exports.explainUSubstitution = nativeBinding.explainUSubstitution
module.exports.extractDivision = nativeBinding.extractDivision
module.exports.extractLinearCoefficients = nativeBinding.extractLinearCoefficients
module.exports.extractNumeratorDenominator = nativeBinding.extractNumeratorDenominator
module.exports.factor = nativeBinding.factor
module.exports.factorial = nativeBinding.factorial
module.exports.factorialWithN = nativeBinding.factorialWithN
module.exports.floor = nativeBinding.floor
module.exports.gamma = nativeBinding.gamma
module.exports.gcd = nativeBinding.gcd
module.exports.getAdaptiveThresholds = nativeBinding.getAdaptiveThresholds
module.exports.getBackgroundComputeStatistics = nativeBinding.getBackgroundComputeStatistics
module.exports.getBackgroundResult = nativeBinding.getBackgroundResult
module.exports.getBackgroundResultByExpression = nativeBinding.getBackgroundResultByExpression
module.exports.getCachedFunctionName = nativeBinding.getCachedFunctionName
module.exports.getCachedResult = nativeBinding.getCachedResult
module.exports.getConfigInfo = nativeBinding.getConfigInfo
module.exports.getGlobalConfig = nativeBinding.getGlobalConfig
module.exports.getGpuCapabilities = nativeBinding.getGpuCapabilities
module.exports.getGpuStatistics = nativeBinding.getGpuStatistics
module.exports.getPdeMessage = nativeBinding.getPdeMessage
module.exports.getPerformanceMetrics = nativeBinding.getPerformanceMetrics
module.exports.getPerformanceSummary = nativeBinding.getPerformanceSummary
module.exports.getPersistentCachedResult = nativeBinding.getPersistentCachedResult
module.exports.getProfilerStatistics = nativeBinding.getProfilerStatistics
module.exports.groebnerBasis = nativeBinding.groebnerBasis
module.exports.initPerformanceOptimizer = nativeBinding.initPerformanceOptimizer
module.exports.integrateLinearFactor = nativeBinding.integrateLinearFactor
module.exports.integrateRational = nativeBinding.integrateRational
module.exports.integrateRationalWithNumeratorDenominatorVar = nativeBinding.integrateRationalWithNumeratorDenominatorVar
module.exports.integrateRepeatedQuadratic = nativeBinding.integrateRepeatedQuadratic
module.exports.integrateSimpleQuadratic = nativeBinding.integrateSimpleQuadratic
module.exports.integrateWithStrategy = nativeBinding.integrateWithStrategy
module.exports.isGpuAvailable = nativeBinding.isGpuAvailable
module.exports.isJustVariable = nativeBinding.isJustVariable
module.exports.isOne = nativeBinding.isOne
module.exports.isPolynomial = nativeBinding.isPolynomial
module.exports.isPolynomialWithExprVar = nativeBinding.isPolynomialWithExprVar
module.exports.isprime = nativeBinding.isprime
module.exports.isRationalFunction = nativeBinding.isRationalFunction
module.exports.isRationalFunctionWithExprVar = nativeBinding.isRationalFunctionWithExprVar
module.exports.lanczosGamma = nativeBinding.lanczosGamma
module.exports.lcm = nativeBinding.lcm
module.exports.ln = nativeBinding.ln
module.exports.log10 = nativeBinding.log10
module.exports.meetsParallelThreshold = nativeBinding.meetsParallelThreshold
module.exports.methodOfCharacteristics = nativeBinding.methodOfCharacteristics
module.exports.modulo = nativeBinding.modulo
module.exports.parse = nativeBinding.parse
module.exports.pascalToSnakeCase = nativeBinding.pascalToSnakeCase
module.exports.polygamma = nativeBinding.polygamma
module.exports.polynomialDegree = nativeBinding.polynomialDegree
module.exports.polynomialDiv = nativeBinding.polynomialDiv
module.exports.polynomialDivWithDividendDivisorVar = nativeBinding.polynomialDivWithDividendDivisorVar
module.exports.polynomialEvaluateAt = nativeBinding.polynomialEvaluateAt
module.exports.polynomialGcd = nativeBinding.polynomialGcd
module.exports.polynomialGcdWithABVar = nativeBinding.polynomialGcdWithABVar
module.exports.polynomialInterpolate = nativeBinding.polynomialInterpolate
module.exports.polynomialQuo = nativeBinding.polynomialQuo
module.exports.polynomialQuoWithDividendDivisorVar = nativeBinding.polynomialQuoWithDividendDivisorVar
module.exports.polynomialRem = nativeBinding.polynomialRem
module.exports.polynomialRemWithDividendDivisorVar = nativeBinding.polynomialRemWithDividendDivisorVar
module.exports.predictAndPrecompute = nativeBinding.predictAndPrecompute
module.exports.resolveSpecialFunction = nativeBinding.resolveSpecialFunction
module.exports.resolveStandardFunction = nativeBinding.resolveStandardFunction
module.exports.resolveWolframFunction = nativeBinding.resolveWolframFunction
module.exports.roots = nativeBinding.roots
module.exports.roots = nativeBinding.roots
module.exports.round = nativeBinding.round
module.exports.savePersistentCache = nativeBinding.savePersistentCache
module.exports.setBindingConfig = nativeBinding.setBindingConfig
module.exports.setGlobalConfig = nativeBinding.setGlobalConfig
module.exports.shouldUseSimd = nativeBinding.shouldUseSimd
module.exports.sign = nativeBinding.sign
module.exports.simplifyAbs = nativeBinding.simplifyAbs
module.exports.simplifySqrt = nativeBinding.simplifySqrt
module.exports.sin = nativeBinding.sin
module.exports.sinh = nativeBinding.sinh
module.exports.solveSturmLiouville = nativeBinding.solveSturmLiouville
module.exports.sqrt = nativeBinding.sqrt
module.exports.storePersistentCachedResult = nativeBinding.storePersistentCachedResult
module.exports.submitBackgroundTask = nativeBinding.submitBackgroundTask
module.exports.substituteVariable = nativeBinding.substituteVariable
module.exports.symbol = nativeBinding.symbol
module.exports.symbols = nativeBinding.symbols
module.exports.tan = nativeBinding.tan
module.exports.tanh = nativeBinding.tanh
module.exports.tryByParts = nativeBinding.tryByParts
module.exports.tryExtractQuadratic = nativeBinding.tryExtractQuadratic
module.exports.tryRegistryIntegration = nativeBinding.tryRegistryIntegration
module.exports.tryRischIntegration = nativeBinding.tryRischIntegration
module.exports.trySubstitution = nativeBinding.trySubstitution
module.exports.tryTableLookup = nativeBinding.tryTableLookup
module.exports.tryTrigonometricIntegration = nativeBinding.tryTrigonometricIntegration
module.exports.univariateGcd = nativeBinding.univariateGcd
module.exports.univariateGcdModular = nativeBinding.univariateGcdModular
module.exports.zeta = nativeBinding.zeta
module.exports.zetaNumerical = nativeBinding.zetaNumerical
