/* auto-generated by NAPI-RS */
/* eslint-disable */
/** JavaScript wrapper for Expression */
export declare class JsExpression {
  /**
   * Create a new expression from an integer
   *
   * # Examples
   *
   * ```javascript
   * const expr = JsExpression.integer(42);
   * ```
   */
  static integer(value: number): JsExpression
  /**
   * Create a new expression from a symbol
   *
   * # Examples
   *
   * ```javascript
   * const x = JsExpression.symbol("x");
   * const alpha = JsExpression.symbol("α");
   * ```
   */
  static symbol(name: string): JsExpression
  /**
   * Add two expressions
   *
   * # Examples
   *
   * ```javascript
   * const x = JsExpression.symbol("x");
   * const two = JsExpression.integer(2);
   * const result = x.add(two);
   * ```
   */
  add(other: JsExpression): JsExpression
  /**
   * Multiply two expressions
   *
   * # Examples
   *
   * ```javascript
   * const x = JsExpression.symbol("x");
   * const three = JsExpression.integer(3);
   * const result = x.multiply(three);
   * ```
   */
  multiply(other: JsExpression): JsExpression
  /**
   * Raise expression to a power
   *
   * # Examples
   *
   * ```javascript
   * const x = JsExpression.symbol("x");
   * const two = JsExpression.integer(2);
   * const xSquared = x.pow(two);
   * ```
   */
  pow(exponent: JsExpression): JsExpression
  /**
   * Simplify the expression
   *
   * # Examples
   *
   * ```javascript
   * const expr = JsExpression.integer(2).add(JsExpression.integer(3));
   * const simplified = expr.simplify();
   * ```
   */
  simplify(): JsExpression
  /**
   * Parse a mathematical expression from string with automatic language detection
   *
   * # Examples
   *
   * ```javascript
   * const expr1 = JsExpression.parse("2*x + sin(y)");
   * const expr2 = JsExpression.parse("\\frac{x^2}{2}");    // LaTeX auto-detected
   * const expr3 = JsExpression.parse("Sin[x] + Cos[y]");   // Wolfram auto-detected
   * ```
   */
  static parse(input: string): JsExpression
  /**
   * Parse with explicit language specification
   *
   * # Examples
   *
   * ```javascript
   * const latex = JsExpression.parseWithLanguage("\\sin(x)", "latex");
   * const wolfram = JsExpression.parseWithLanguage("Sin[x]", "wolfram");
   * const simple = JsExpression.parseWithLanguage("sin(x)", "simple");
   * ```
   */
  static parseWithLanguage(input: string, language: string): JsExpression
  /**
   * Convert expression to LaTeX format
   *
   * # Examples
   *
   * ```javascript
   * const expr = JsExpression.symbol("x").pow(JsExpression.integer(2));
   * const latex = expr.toLatex();  // Returns "x^{2}"
   * ```
   */
  toLatex(): string
  /**
   * Convert expression to simple mathematical notation
   *
   * # Examples
   *
   * ```javascript
   * const expr = JsExpression.symbol("x").pow(JsExpression.integer(2));
   * const simple = expr.toSimple();  // Returns "x^2"
   * ```
   */
  toSimple(): string
  /**
   * Convert expression to Wolfram Language format
   *
   * # Examples
   *
   * ```javascript
   * const expr = JsExpression.function("sin", [JsExpression.symbol("x")]);
   * const wolfram = expr.toWolfram();  // Returns "Sin[x]"
   * ```
   */
  toWolfram(): string
  /**
   * Create an equation (equality relation)
   *
   * # Examples
   *
   * ```javascript
   * const x = JsExpression.symbol("x");
   * const five = JsExpression.integer(5);
   * const equation = JsExpression.equation(x, five);
   * ```
   */
  static equation(left: JsExpression, right: JsExpression): JsExpression
  /**
   * String representation
   *
   * # Examples
   *
   * ```javascript
   * const x = JsExpression.symbol("x");
   * console.log(x.toString());
   * ```
   */
  toString(): string
}

/** JavaScript wrapper for MathSolver */
export declare class JsMathSolver {
  /**
   * Create a new solver
   *
   * # Examples
   *
   * ```javascript
   * const solver = new JsMathSolver();
   * ```
   */
  constructor()
  /**
   * Solve an equation
   *
   * # Examples
   *
   * ```javascript
   * const solver = new JsMathSolver();
   * const x = JsExpression.symbol("x");
   * const five = JsExpression.integer(5);
   * const equation = JsExpression.equation(x, five);
   * const result = solver.solve(equation, "x");
   * ```
   */
  solve(equation: JsExpression, variable: string): string
}
