/* auto-generated by NAPI-RS */
/* eslint-disable */
/** JavaScript wrapper for Expression */
export declare class JsExpression {
  /**
   * Create a new expression from an integer
   *
   * # Examples
   *
   * ```javascript
   * const expr = JsExpression.integer(42);
   * ```
   */
  static integer(value: number): JsExpression
  /**
   * Create a new expression from a symbol
   *
   * # Examples
   *
   * ```javascript
   * const x = JsExpression.symbol("x");
   * const alpha = JsExpression.symbol("α");
   * ```
   */
  static symbol(name: string): JsExpression
  /**
   * Add two expressions
   *
   * # Examples
   *
   * ```javascript
   * const x = JsExpression.symbol("x");
   * const two = JsExpression.integer(2);
   * const result = x.add(two);
   * ```
   */
  add(other: JsExpression): JsExpression
  /**
   * Multiply two expressions
   *
   * # Examples
   *
   * ```javascript
   * const x = JsExpression.symbol("x");
   * const three = JsExpression.integer(3);
   * const result = x.multiply(three);
   * ```
   */
  multiply(other: JsExpression): JsExpression
  /**
   * Raise expression to a power
   *
   * # Examples
   *
   * ```javascript
   * const x = JsExpression.symbol("x");
   * const two = JsExpression.integer(2);
   * const xSquared = x.pow(two);
   * ```
   */
  pow(exponent: JsExpression): JsExpression
  /**
   * Simplify the expression
   *
   * # Examples
   *
   * ```javascript
   * const expr = JsExpression.integer(2).add(JsExpression.integer(3));
   * const simplified = expr.simplify();
   * ```
   */
  simplify(): JsExpression
  /**
   * Create an equation (equality relation)
   *
   * # Examples
   *
   * ```javascript
   * const x = JsExpression.symbol("x");
   * const five = JsExpression.integer(5);
   * const equation = JsExpression.equation(x, five);
   * ```
   */
  static equation(left: JsExpression, right: JsExpression): JsExpression
  /**
   * String representation
   *
   * # Examples
   *
   * ```javascript
   * const x = JsExpression.symbol("x");
   * console.log(x.toString());
   * ```
   */
  toString(): string
}

/** JavaScript wrapper for MathParser */
export declare class JsMathParser {
  /**
   * Create a new parser
   *
   * # Examples
   *
   * ```javascript
   * const parser = new JsMathParser();
   * ```
   */
  constructor()
  /**
   * Parse a mathematical expression
   *
   * # Examples
   *
   * ```javascript
   * const parser = new JsMathParser();
   * const expr = parser.parse("x + 2", "standard");
   * const latexExpr = parser.parse("\\frac{x}{2}", "latex");
   * ```
   */
  parse(input: string, language: string): JsExpression
}

/** JavaScript wrapper for MathSolver */
export declare class JsMathSolver {
  /**
   * Create a new solver
   *
   * # Examples
   *
   * ```javascript
   * const solver = new JsMathSolver();
   * ```
   */
  constructor()
  /**
   * Solve an equation
   *
   * # Examples
   *
   * ```javascript
   * const solver = new JsMathSolver();
   * const x = JsExpression.symbol("x");
   * const five = JsExpression.integer(5);
   * const equation = JsExpression.equation(x, five);
   * const result = solver.solve(equation, "x");
   * ```
   */
  solve(equation: JsExpression, variable: string): string
}
