/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class JsExpression {
  /** Create a new expression from an integer */
  static integer(value: number): JsExpression
  /** Create a new expression from a symbol */
  static symbol(name: string): JsExpression
  /** Add two expressions */
  add(other: JsExpression): JsExpression
  /** Multiply two expressions */
  multiply(other: JsExpression): JsExpression
  /** Raise expression to a power */
  pow(exponent: JsExpression): JsExpression
  /** Simplify the expression */
  simplify(): JsExpression
  /** Create an equation (equality relation) */
  static equation(left: JsExpression, right: JsExpression): JsExpression
  /** String representation */
  toString(): string
}
export class JsMathSolver {
  /** Create a new solver */
  constructor()
  /** Solve an equation */
  solve(equation: JsExpression, variable: string): string
}
export class JsMathParser {
  /** Create a new parser */
  constructor()
  /** Parse a mathematical expression */
  parse(input: string, language: string): JsExpression
}