name: 'Python Setup'
description: 'Set up Python with caching'

inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.11'
  cache-dependency-path:
    description: 'Path to requirements for caching'
    required: false
    default: '**/requirements*.txt'

outputs:
  python-version:
    description: 'Installed Python version'
    value: ${{ steps.setup.outputs.python-version }}
  cache-hit:
    description: 'Whether cache was hit'
    value: ${{ steps.setup.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      id: setup
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
