name: 'Node.js Setup'
description: 'Set up Node.js with caching'

inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '20'
  registry-url:
    description: 'Registry URL for publishing'
    required: false
    default: ''
  cache-dependency-path:
    description: 'Path to package-lock.json for caching'
    required: false
    default: 'crates/mathhook-node/package-lock.json'

outputs:
  node-version:
    description: 'Installed Node.js version'
    value: ${{ steps.setup.outputs.node-version }}
  cache-hit:
    description: 'Whether cache was hit'
    value: ${{ steps.setup.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      id: setup
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af  # v4.1.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
